In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\deban_o\Downloads\DataCoSupplyChainDataset.csv", encoding = 'latin-1')
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [6]:
print(df.shape)

(180519, 53)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [8]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [9]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Order Id                              0
Order Country                         0
Order Customer Id                     0
Customer Fname                        0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Id                           0
Days for shipping (real)              0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Shipping Mode                         0
dtype: int64

In [10]:
to_drop = [
    'Order Id', 'Customer City', 'Category Id', 'Order Item Cardprod Id', 'Order Item Id','Order Zipcode',
 'Customer Country', 'Customer Id', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Order Customer Id',
    'Department Name', 'Latitude', 'Longitude','Customer Fname','Customer Lname', 'Customer Password','Customer Email','Product Card Id',
       'Product Category Id', 'Product Description', 'Product Image'
    
]
# Drop the columns

df.drop(columns=to_drop, inplace=True)

# Check the remaining columns
print(df.columns)

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer Segment', 'Market',
       'Order City', 'Order Country', 'order date (DateOrders)',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [11]:
df.isnull().sum().sort_values(ascending=False)

Type                             0
Order Item Product Price         0
shipping date (DateOrders)       0
Product Status                   0
Product Price                    0
Product Name                     0
Order Status                     0
Order State                      0
Order Region                     0
Order Profit Per Order           0
Order Item Total                 0
Sales                            0
Order Item Quantity              0
Order Item Profit Ratio          0
Order Item Discount Rate         0
Days for shipping (real)         0
Order Item Discount              0
order date (DateOrders)          0
Order Country                    0
Order City                       0
Market                           0
Customer Segment                 0
Category Name                    0
Late_delivery_risk               0
Delivery Status                  0
Sales per customer               0
Benefit per order                0
Days for shipment (scheduled)    0
Shipping Mode                    0
dtype: int64

In [12]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Name                     object
Customer Segment                  object
Market                            object
Order City                        object
Order Country                     object
order date (DateOrders)           object
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [13]:
df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])

In [14]:
df.dtypes

Type                                     object
Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Sales per customer                      float64
Delivery Status                          object
Late_delivery_risk                        int64
Category Name                            object
Customer Segment                         object
Market                                   object
Order City                               object
Order Country                            object
order date (DateOrders)          datetime64[ns]
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Product Price                float64
Order Item Profit Ratio                 float64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Profit Per Order                  float64
Order Region                             object
Order State                              object
Order Status                             object
Product Name                             object
Product Price                           float64
Product Status                            int64
shipping date (DateOrders)       datetime64[ns]
Shipping Mode                            object
dtype: object

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Delay Days'] = df['Days for shipping (real)'] - df['Days for shipment (scheduled)']

In [17]:
df['Is Late'] = df['Delay Days'] > 0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Name                  180519 non-null  object
 8   Customer Segment               180519 non-null  object
 9   Market                         180519 non-null  object
 10  Order City                     180519 non-null  object
 11  Order Country                  180519 non-null  object
 12  order date (DateOrders)        180519 non-null  datetime64[ns]
 13  Order Item Discount            180519 non-null  float64
 14  Order Item Discount Rate       180519 non-null  float64
 15  Order Item Product Price       180519 non-null  float64
 16  Order Item Profit Ratio        180519 non-null  float64
 17  Order Item Quantity            180519 non-null  int64
 18  Sales                          180519 non-null  float64
 19  Order Item Total               180519 non-null  float64
 20  Order Profit Per Order         180519 non-null  float64
 21  Order Region                   180519 non-null  object
 22  Order State                    180519 non-null  object
 23  Order Status                   180519 non-null  object
 24  Product Name                   180519 non-null  object
 25  Product Price                  180519 non-null  float64
 26  Product Status                 180519 non-null  int64
 27  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 28  Shipping Mode                  180519 non-null  object
 29  Delay Days                     180519 non-null  int64
 30  Is Late                        180519 non-null  bool
dtypes: bool(1), datetime64[ns](2), float64(10), int64(6), object(12)
memory usage: 41.5+ MB

In [19]:
df[['Delay Days', 'Is Late']].head()

   Delay Days  Is Late
0          -1    False
1           1     True
2           0    False
3          -1    False
4          -2    False

In [20]:
df['Delay Days'].describe()

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Delay Days, dtype: float64

In [21]:
df['Shipping Mode'].value_counts(normalize=True) * 100

Shipping Mode
Standard Class    59.690116
Second Class      19.508196
First Class       15.407796
Same Day           5.393892
Name: proportion, dtype: float64

In [22]:
df['Order Region'].value_counts(normalize=True) * 100

Order Region
Central America    15.699732
Western Europe     15.017256
South America       8.273367
Oceania             5.621569
Northern Europe     5.424360
Southeast Asia      5.284208
Southern Europe     5.224381
Caribbean           4.607825
West of USA         4.427789
South Asia          4.282652
Eastern Asia        4.032816
East of USA         3.830622
West Asia           3.328735
US Center           3.261153
South of  USA       2.240761
Eastern Europe      2.171517
West Africa         2.047430
North Africa        1.790393
East Africa         1.025931
Central Africa      0.928988
Southern Africa     0.640930
Canada              0.531246
Central Asia        0.306339
Name: proportion, dtype: float64

In [23]:
df[['Sales', 'Order Profit Per Order']].describe()

               Sales  Order Profit Per Order
count  180519.000000           180519.000000
mean      203.772096               21.974989
std       132.273077              104.433526
min         9.990000            -4274.979980
25%       119.980003                7.000000
50%       199.919998               31.520000
75%       299.950012               64.800003
max      1999.989990              911.799988

In [24]:
df['Is Late'].mean() * 100

np.float64(57.279289160697765)

In [25]:
df.groupby('Shipping Mode')['Delay Days'].mean().sort_values(ascending=False)

Shipping Mode
Second Class      1.990828
First Class       1.000000
Same Day          0.478279
Standard Class   -0.004093
Name: Delay Days, dtype: float64

In [26]:
df.groupby('Order Region')['Delay Days'].mean().sort_values(ascending=False)

Order Region
Central Asia       0.645570
Central Africa     0.639833
South Asia         0.597465
Western Europe     0.597403
US Center          0.587226
East of USA        0.584816
South of  USA      0.579975
Eastern Europe     0.579847
East Africa        0.570734
West Asia          0.569479
Eastern Asia       0.566484
Central America    0.561942
Southeast Asia     0.558235
West of USA        0.557238
South America      0.556344
Oceania            0.556267
North Africa       0.552290
West Africa        0.550595
Northern Europe    0.546875
Caribbean          0.546526
Southern Europe    0.515640
Southern Africa    0.478825
Canada             0.391032
Name: Delay Days, dtype: float64

In [27]:
df.groupby('Order Region')['Is Late'].mean() * 100

Order Region
Canada             51.929093
Caribbean          55.878817
Central Africa     60.703637
Central America    57.245686
Central Asia       57.142857
East Africa        57.451404
East of USA        57.975416
Eastern Asia       56.730769
Eastern Europe     57.448980
North Africa       56.683168
Northern Europe    56.413399
Oceania            56.109578
South America      57.234684
South Asia         58.504721
South of  USA      58.096415
Southeast Asia     57.983017
Southern Africa    56.266206
Southern Europe    56.727813
US Center          57.125871
West Africa        55.005411
West Asia          57.497088
West of USA        56.599525
Western Europe     58.515622
Name: Is Late, dtype: float64

In [28]:
df.groupby('Category Name')['Delay Days'].mean().sort_values(ascending=False)

Category Name
Golf Bags & Carts       0.770492
Soccer                  0.717391
Pet Supplies            0.709350
Strength Training       0.666667
Boxing & MMA            0.666667
As Seen on  TV!         0.661765
Lacrosse                0.658892
Women's Clothing        0.652308
Tennis & Racquet        0.649390
Cameras                 0.645270
Consumer Electronics    0.638051
Crafts                  0.634298
Trade-In                0.631417
Kids' Golf Clubs        0.619792
Sporting Goods          0.619048
Golf Gloves             0.615888
Fitness Accessories     0.614887
Accessories             0.589326
Girls' Apparel          0.585346
Baseball & Softball     0.583861
Children's Clothing     0.579755
Golf Shoes              0.578244
Cleats                  0.576962
Video Games             0.576372
Shop By Sport           0.575291
Music                   0.573733
Electronics             0.571926
Water Sports            0.567310
Indoor/Outdoor Games    0.564722
Men's Footwear          0.564191
Hunting & Shooting      0.561364
Women's Apparel         0.559544
Women's Golf Clubs      0.558011
Fishing                 0.555152
Cardio Equipment        0.554337
Toys                    0.551985
Camping & Hiking        0.551388
Garden                  0.549587
Golf Balls              0.547797
Books                   0.533333
Health and Beauty       0.533149
DVDs                    0.530021
Men's Clothing          0.514423
Basketball              0.477612
Golf Apparel            0.473923
Hockey                  0.469055
CDs                     0.461255
Computers               0.454751
Baby                    0.444444
Men's Golf Clubs        0.325088
Name: Delay Days, dtype: float64

In [29]:
df.groupby('Is Late')['Order Profit Per Order'].mean()

Is Late
False    22.496873
True     21.585751
Name: Order Profit Per Order, dtype: float64

In [30]:
df.groupby('Shipping Mode')['Is Late'].mean() * 100

Shipping Mode
First Class       100.000000
Same Day           47.827873
Second Class       79.730804
Standard Class     39.768171
Name: Is Late, dtype: float64

In [31]:
df.groupby('Customer Segment')['Is Late'].mean() * 100

Customer Segment
Consumer       57.294875
Corporate      57.111829
Home Office    57.518774
Name: Is Late, dtype: float64

In [32]:
df.groupby('Customer Segment')['Delay Days'].mean()

Customer Segment
Consumer       0.564917
Corporate      0.560185
Home Office    0.577949
Name: Delay Days, dtype: float64

In [33]:
df.groupby('Category Name')['Is Late'].mean().sort_values(ascending=False)

Category Name
Golf Bags & Carts       0.688525
Lacrosse                0.620991
Cameras                 0.619932
Pet Supplies            0.613821
Sporting Goods          0.599440
Basketball              0.597015
Fitness Accessories     0.595469
Crafts                  0.595041
Strength Training       0.594595
Music                   0.594470
Boxing & MMA            0.593381
Consumer Electronics    0.591647
Accessories             0.591573
As Seen on  TV!         0.588235
Girls' Apparel          0.586178
Women's Clothing        0.586154
Health and Beauty       0.585635
Electronics             0.585234
Trade-In                0.584189
Toys                    0.584121
Golf Gloves             0.584112
Hunting & Shooting      0.584091
Kids' Golf Clubs        0.583333
Tennis & Racquet        0.579268
Golf Shoes              0.578244
Shop By Sport           0.576111
Books                   0.575309
Golf Balls              0.574237
Cleats                  0.573337
Fishing                 0.573160
Indoor/Outdoor Games    0.572235
Water Sports            0.572136
Women's Apparel         0.571286
Garden                  0.570248
Cardio Equipment        0.569392
Men's Footwear          0.569271
Women's Golf Clubs      0.569061
Camping & Hiking        0.569014
Men's Clothing          0.567308
Children's Clothing     0.565951
Baseball & Softball     0.564873
Video Games             0.563246
DVDs                    0.563147
Soccer                  0.557971
Hockey                  0.557003
Baby                    0.545894
CDs                     0.542435
Golf Apparel            0.532880
Computers               0.527149
Men's Golf Clubs        0.498233
Name: Is Late, dtype: float64

In [34]:
df.groupby(['Shipping Mode', 'Is Late'])['Order Profit Per Order'].mean()

Shipping Mode   Is Late
First Class     True       23.122238
Same Day        False      22.991908
                True       18.513966
Second Class    False      22.600615
                True       20.976743
Standard Class  False      22.446715
                True       21.321328
Name: Order Profit Per Order, dtype: float64

In [35]:
df.groupby('Order Region').agg({
    'Is Late': 'mean',
    'Sales': 'sum'
}).sort_values(by='Is Late', ascending=False)

                  Is Late         Sales
Order Region
Central Africa   0.607036  3.272630e+05
Western Europe   0.585156  5.894381e+06
South Asia       0.585047  1.553681e+06
South of  USA    0.580964  7.857839e+05
Southeast Asia   0.579830  1.932496e+06
East of USA      0.579754  1.371112e+06
West Asia        0.574971  1.174672e+06
East Africa      0.574514  3.762349e+05
Eastern Europe   0.574490  7.742666e+05
Central America  0.572457  5.665712e+06
South America    0.572347  2.960881e+06
Central Asia     0.571429  1.098399e+05
US Center        0.571259  1.151356e+06
Eastern Asia     0.567308  1.486401e+06
Southern Europe  0.567278  2.047919e+06
North Africa     0.566832  6.347522e+05
West of USA      0.565995  1.571416e+06
Northern Europe  0.564134  2.155831e+06
Southern Africa  0.562662  2.282516e+05
Oceania          0.561096  2.016654e+06
Caribbean        0.558788  1.651019e+06
West Africa      0.550054  7.279512e+05
Canada           0.519291  1.868610e+05

In [37]:
df[['Delay Days', 'Order Item Quantity', 'Order Item Discount', 'Sales', 'Order Profit Per Order']].corr()  #Correlation Analysis

,Delay Days,Order Item Quantity,Order Item Discount,Sales,Order Profit Per Order
Delay Days,1.000000,0.001813,-0.000241,-0.003695,-0.005385
Order Item Quantity,0.001813,1.000000,0.065379,0.106442,0.015696
Order Item Discount,-0.000241,0.065379,1.000000,0.617438,0.064756
Sales,-0.003695,0.106442,0.617438,1.000000,0.131816
Order Profit Per Order,-0.005385,0.015696,0.064756,0.131816,1.000000

In [38]:
df[['Delay Days', 'Sales', 'Order Profit Per Order']].describe() #Descriptive Statistics

          Delay Days          Sales  Order Profit Per Order
count  180519.000000  180519.000000           180519.000000
mean        0.565807     203.772096               21.974989
std         1.490966     132.273077              104.433526
min        -2.000000       9.990000            -4274.979980
25%         0.000000     119.980003                7.000000
50%         1.000000     199.919998               31.520000
75%         1.000000     299.950012               64.800003
max         4.000000    1999.989990              911.799988

In [39]:
 # Outlier Detection using IQR method
Q1 = df['Order Profit Per Order'].quantile(0.25)
Q3 = df['Order Profit Per Order'].quantile(0.75)
IQR = Q3 - Q1

lower_boundary = Q1 - 1.5 * IQR
upper_boundary = Q3 + 1.5 * IQR

outliers = df[(df['Order Profit Per Order'] < lower_boundary) | 
              (df['Order Profit Per Order'] > upper_boundary)]

print(f'Q1: {Q1}')
print(f'Q3: {Q3}')
print(f'IQR: {IQR}')
print(f'Lower Boundary: {lower_boundary}')
print(f'Upper Boundary: {upper_boundary}')
print(f'Number of Outliers: {len(outliers)}')
print(f'Percentage of Outliers: {len(outliers)/len(df)*100:.2f}%')

Q1: 7.0
Q3: 64.80000305
IQR: 57.80000305
Lower Boundary: -79.70000457500001
Upper Boundary: 151.50000762500002
Number of Outliers: 18942
Percentage of Outliers: 10.49%

In [40]:
# Skewness and Kurtosis
skewness = df[['Delay Days', 'Sales', 'Order Profit Per Order']].skew()
kurtosis = df[['Delay Days', 'Sales', 'Order Profit Per Order']].kurt()

print("Skewness:")
print(skewness)
print("\nKurtosis:")
print(kurtosis)

Skewness:
Delay Days                0.031464
Sales                     2.884249
Order Profit Per Order   -4.741834
dtype: float64

Kurtosis:
Delay Days                -0.292237
Sales                     23.936561
Order Profit Per Order    71.377259
dtype: float64

In [41]:
print("Mean:")
print(df[['Delay Days', 'Sales', 'Order Profit Per Order']].mean())
print("\nMedian:")
print(df[['Delay Days', 'Sales', 'Order Profit Per Order']].median())

Mean:
Delay Days                  0.565807
Sales                     203.772096
Order Profit Per Order     21.974989
dtype: float64

Median:
Delay Days                  1.000000
Sales                     199.919998
Order Profit Per Order     31.520000
dtype: float64

In [42]:
df.groupby('Is Late')['Order Profit Per Order'].agg(['mean', 'median'])

              mean  median
Is Late
False    22.496873   31.68
True     21.585751   31.43

In [64]:
# Shipping Mode Segmentation 
Shipping_performance = df.groupby('Shipping Mode')['Is Late'].mean() * 100
Shipping_performance= Shipping_performance.sort_values(ascending=False)
Shipping_performance

Shipping Mode
First Class       100.000000
Second Class       79.730804
Same Day           47.827873
Standard Class     39.768171
Name: Is Late, dtype: float64

In [66]:
def classify_risk(x):
    if x >= 70:
        return 'High Risk'
    elif x >= 50:
        return 'Medium Risk'
    else:
        return 'Low Risk'
      
Shipping_segment = Shipping_performance.reset_index()
Shipping_segment['Risk Level'] = Shipping_segment['Is Late'].apply(classify_risk)
Shipping_segment

    Shipping Mode     Is Late Risk Level
0     First Class  100.000000  High Risk
1    Second Class   79.730804  High Risk
2        Same Day   47.827873   Low Risk
3  Standard Class   39.768171   Low Risk

In [68]:
region_performance = df.groupby('Order Region')['Is Late'].mean() * 100
region_performance = region_performance.sort_values(ascending=False)
region_performance

Order Region
Central Africa     60.703637
Western Europe     58.515622
South Asia         58.504721
South of  USA      58.096415
Southeast Asia     57.983017
East of USA        57.975416
West Asia          57.497088
East Africa        57.451404
Eastern Europe     57.448980
Central America    57.245686
South America      57.234684
Central Asia       57.142857
US Center          57.125871
Eastern Asia       56.730769
Southern Europe    56.727813
North Africa       56.683168
West of USA        56.599525
Northern Europe    56.413399
Southern Africa    56.266206
Oceania            56.109578
Caribbean          55.878817
West Africa        55.005411
Canada             51.929093
Name: Is Late, dtype: float64

In [70]:
region_segment = region_performance.reset_index()
region_segment['Risk Level'] = region_segment['Is Late'].apply(classify_risk)

region_segment

       Order Region    Is Late   Risk Level
0    Central Africa  60.703637  Medium Risk
1    Western Europe  58.515622  Medium Risk
2        South Asia  58.504721  Medium Risk
3    South of  USA   58.096415  Medium Risk
4    Southeast Asia  57.983017  Medium Risk
5       East of USA  57.975416  Medium Risk
6         West Asia  57.497088  Medium Risk
7       East Africa  57.451404  Medium Risk
8    Eastern Europe  57.448980  Medium Risk
9   Central America  57.245686  Medium Risk
10    South America  57.234684  Medium Risk
11     Central Asia  57.142857  Medium Risk
12       US Center   57.125871  Medium Risk
13     Eastern Asia  56.730769  Medium Risk
14  Southern Europe  56.727813  Medium Risk
15     North Africa  56.683168  Medium Risk
16     West of USA   56.599525  Medium Risk
17  Northern Europe  56.413399  Medium Risk
18  Southern Africa  56.266206  Medium Risk
19          Oceania  56.109578  Medium Risk
20        Caribbean  55.878817  Medium Risk
21      West Africa  55.005411  Medium Risk
22           Canada  51.929093  Medium Risk

In [72]:
category_performance = df.groupby('Category Name')['Delay Days'].mean().sort_values(ascending=False)

category_segment = category_performance.reset_index()
category_segment

           Category Name  Delay Days
0      Golf Bags & Carts    0.770492
1                 Soccer    0.717391
2           Pet Supplies    0.709350
3      Strength Training    0.666667
4           Boxing & MMA    0.666667
5        As Seen on  TV!    0.661765
6               Lacrosse    0.658892
7       Women's Clothing    0.652308
8       Tennis & Racquet    0.649390
9               Cameras     0.645270
10  Consumer Electronics    0.638051
11                Crafts    0.634298
12              Trade-In    0.631417
13      Kids' Golf Clubs    0.619792
14        Sporting Goods    0.619048
15           Golf Gloves    0.615888
16   Fitness Accessories    0.614887
17           Accessories    0.589326
18        Girls' Apparel    0.585346
19   Baseball & Softball    0.583861
20   Children's Clothing    0.579755
21            Golf Shoes    0.578244
22                Cleats    0.576962
23           Video Games    0.576372
24         Shop By Sport    0.575291
25                 Music    0.573733
26           Electronics    0.571926
27          Water Sports    0.567310
28  Indoor/Outdoor Games    0.564722
29        Men's Footwear    0.564191
30    Hunting & Shooting    0.561364
31       Women's Apparel    0.559544
32    Women's Golf Clubs    0.558011
33               Fishing    0.555152
34      Cardio Equipment    0.554337
35                  Toys    0.551985
36      Camping & Hiking    0.551388
37                Garden    0.549587
38            Golf Balls    0.547797
39                Books     0.533333
40     Health and Beauty    0.533149
41                  DVDs    0.530021
42        Men's Clothing    0.514423
43            Basketball    0.477612
44          Golf Apparel    0.473923
45                Hockey    0.469055
46                  CDs     0.461255
47             Computers    0.454751
48                 Baby     0.444444
49      Men's Golf Clubs    0.325088